# Generated by Django 6.1 on 2026-08-17 15:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationrequest',
            name='verification_method',
            field=models.CharField(choices=[('ekyc_document', 'eKYC — Document scan'), ('ekyc_selfie', 'eKYC — Selfie liveness check'), ('did_vc_import', 'Import existing DID/Verifiable Credential')], default='ekyc_document', max_length=20),
        ),
        migrations.CreateModel(
            name='VerifiableCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_id', models.CharField(default=uuid.uuid4, editable=False, max_length=64, unique=True)),
                ('issuer_did', models.CharField(default='did:mock:jvcp-platform', max_length=100)),
                ('subject_did', models.CharField(blank=True, max_length=100)),
                ('claims', models.JSONField(default=dict)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('revoked', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='identity.identityprofile')),
            ],
        ),
    ]
