# Generated by Django 6.1 on 2026-08-17 15:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RemittanceTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=150)),
                ('recipient_account_ref', models.CharField(help_text='Mock account reference — never a real bank number', max_length=100)),
                ('direction', models.CharField(choices=[('jp_to_vn', 'Japan → Vietnam'), ('vn_to_jp', 'Vietnam → Japan')], max_length=10)),
                ('send_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('send_currency', models.CharField(max_length=3)),
                ('exchange_rate', models.DecimalField(decimal_places=6, max_digits=15)),
                ('service_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('receive_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('receive_currency', models.CharField(max_length=3)),
                ('transaction_id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('initiated', 'Initiated'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='initiated', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transfers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
