# Generated by Django 6.1 on 2026-08-17 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('qr_code', 'QR code (scan to pay)'), ('nfc_tap', 'NFC tap'), ('card_mock', 'Card (mock)')], default='qr_code', max_length=20),
        ),
    ]
