# Generated by Django 6.1 on 2026-08-18 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_analyticsevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('IDENTITY_SUBMITTED', 'Identity Submitted'), ('IDENTITY_APPROVED', 'Identity Approved'), ('IDENTITY_REJECTED', 'Identity Rejected'), ('DID_CREATED', 'DID Created'), ('VC_ISSUED', 'VC Issued'), ('VC_REVOKED', 'VC Revoked'), ('PAYMENT_CREATED', 'Payment Created'), ('PAYMENT_COMPLETED', 'Payment Completed'), ('PAYMENT_FAILED', 'Payment Failed'), ('ORDER_CREATED', 'Order Created'), ('ORDER_COMPLETED', 'Order Completed'), ('REFUND_REQUESTED', 'Refund Requested'), ('REMITTANCE_CREATED', 'Remittance Created'), ('REMITTANCE_COMPLETED', 'Remittance Completed')], max_length=40)),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.CharField(max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('previous_hash', models.CharField(blank=True, max_length=64)),
                ('event_hash', models.CharField(editable=False, max_length=64)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
